version: "2"
linters:
  enable:
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - os.Remove
        - os.RemoveAll
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
