name: gitleaks

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v3
