on: [push, pull_request]
name: Security

jobs:
  security:
    strategy:
      matrix:
        go-version: [1.26.4]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Verify modules
        run: |
          go mod download
          go mod verify

      - name: Run govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

      - name: Run gosec
        run: go run github.com/securego/gosec/v2/cmd/gosec@latest ./...
