on: [push, pull_request]
name: Tests

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.26.4]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Setup Task
        uses: go-task/setup-task@v2

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Test
        run: task test

      - name: Integration test
        run: task integration-test
